#!/usr/bin/env bash
# Generate the skill INDEX.md.
#
# Split-layout aware (engine repo + content overlay):
#   - The COMMITTED engine index ($NERVEPACK/INDEX.md) lists ENGINE skills ONLY.
#     The engine tree is the publishable surface, so it must carry no overlay/
#     personal skills (their descriptions can contain personal data) — the
#     pii-guard CI job enforces this.
#   - In a split layout, a MERGED index (engine + overlay, overlay-wins on a name
#     clash) is also written to the overlay ($(np_content_dir)/INDEX.md) for local
#     discovery — this is the "find existing skills before adding one" catalog used
#     by /np-core-contribute and the weekly-compact agent.
#   - In the legacy single-repo layout (content == engine) there is one index at
#     the engine root, identical to the historical behavior (no second write).
#
# Output is sorted by skill name. Each row: name, line count, description.
# Used by:
#   - 30-link-skills.sh (regenerates whenever the linker runs)
#   - /np-core-contribute (read this BEFORE writing a new skill — find existing
#     skills to extend rather than duplicate)
#   - weekly-compact agent (uses descriptions for similarity scoring)
set -euo pipefail

NERVEPACK="${NERVEPACK:-$HOME/Code/nervepack}"
source "$NERVEPACK/engine/setup/np-content-lib.sh"
ENGINE_SKILLS="$NERVEPACK/skills"
CONTENT_DIR="$(np_content_dir)"
OVERLAY_SKILLS="$CONTENT_DIR/skills"

if [[ ! -d "$ENGINE_SKILLS" ]] && [[ ! -d "$OVERLAY_SKILLS" ]]; then
  echo "no skills/ dir at $ENGINE_SKILLS or $OVERLAY_SKILLS" >&2
  exit 1
fi

extract() {
  # Print "name|description|lines" for a SKILL.md. Frontmatter is
  # delimited by lines that are exactly "---".
  local file="$1"
  awk '
    BEGIN { in_fm = 0; name = ""; desc = "" }
    /^---$/ { in_fm = !in_fm; next }
    in_fm && /^name:/ {
      sub(/^name:[[:space:]]*/, "")
      name = $0
    }
    in_fm && /^description:/ {
      sub(/^description:[[:space:]]*/, "")
      desc = $0
    }
    END {
      gsub(/\|/, "\\|", name)
      gsub(/\|/, "\\|", desc)
      printf "%s|%s|%d\n", name, desc, NR
    }
  ' "$file"
}

render_index() {
  # $1 = output file; remaining args = skill base dirs (precedence: later wins).
  local out="$1"; shift
  local tmp; tmp="$(mktemp)"
  local -A _idx_src
  local base d name skill_file fm_name fm_desc lines

  {
    echo "# nervepack — skill index"
    echo
    echo "Auto-generated by \`setup/60-generate-index.sh\`. Don't edit by hand."
    echo "Re-runs automatically inside \`30-link-skills.sh\`."
    echo
    echo "**Read this before adding a new skill** — find existing skills to"
    echo "extend rather than create overlapping duplicates."
    echo
    echo "| Skill | Lines | Description |"
    echo "|---|---:|---|"

    # Build a deduped name→dir map across the given bases (later wins on clash).
    for base in "$@"; do
      [[ -d "$base" ]] || continue
      shopt -s nullglob
      for d in "$base"/*/; do
        [[ -d "$d" ]] || continue
        _idx_src["$(basename "$d")"]="${d%/}"
      done
      shopt -u nullglob
    done

    for name in "${!_idx_src[@]}"; do
      d="${_idx_src[$name]}"
      skill_file="$d/SKILL.md"
      [[ -f "$skill_file" ]] || continue

      IFS='|' read -r fm_name fm_desc lines < <(extract "$skill_file")
      # Fallbacks if frontmatter is malformed
      [[ -z "$fm_name" ]] && fm_name="$name"
      [[ -z "$fm_desc" ]] && fm_desc="_(no description in frontmatter)_"

      # Warn if frontmatter name doesn't match dirname
      if [[ "$fm_name" != "$name" ]]; then
        fm_name="$name ⚠"
      fi

      printf "| [%s](skills/%s/SKILL.md) | %s | %s |\n" "$fm_name" "$name" "$lines" "$fm_desc"
    done | sort

    echo
    echo "## Archived skills"
    echo
    if [[ -s "$NERVEPACK/archive/MANIFEST.md" ]]; then
      echo "See [archive/MANIFEST.md](archive/MANIFEST.md)."
    else
      echo "_(none yet)_"
    fi
  } > "$tmp"

  mv "$tmp" "$out"
  echo "wrote $out"
}

# Committed engine index: ENGINE skills only (publishable surface, pii-guarded).
render_index "$NERVEPACK/INDEX.md" "$ENGINE_SKILLS"

# Split layout: also write the merged (engine + overlay) index into the overlay for
# local discovery. Skip when content == engine (legacy single-repo) — the engine
# index already covers the full set there.
if [[ "$CONTENT_DIR" != "$NERVEPACK" ]]; then
  render_index "$CONTENT_DIR/INDEX.md" "$ENGINE_SKILLS" "$OVERLAY_SKILLS"
fi
